"""initial_wildlife_schema

Revision ID: 9b66b05e4c67
Revises: 
Create Date: 2026-09-05 16:15:36.916970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b66b05e4c67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_records_animal_id'), table_name='behavior_records')
    op.drop_index(op.f('ix_behavior_records_timestamp'), table_name='behavior_records')
    op.drop_table('behavior_records')
    op.drop_index(op.f('ix_health_metrics_animal_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_date'), table_name='health_metrics')
    op.drop_table('health_metrics')
    op.add_column('alerts', sa.Column('zone_name', sa.String(length=100), nullable=True))
    op.add_column('alerts', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('gps_lon', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('snapshot_path', sa.String(length=500), nullable=True))
    op.add_column('alerts', sa.Column('video_path', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.drop_constraint(op.f('alerts_media_asset_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'media_asset_id')
    op.drop_column('alerts', 'anomaly_score')
    op.add_column('animals', sa.Column('rfid_tag', sa.String(length=64), nullable=True))
    op.add_column('animals', sa.Column('estimated_age', sa.String(length=50), nullable=True))
    op.add_column('animals', sa.Column('age_confidence', sa.Float(), nullable=True))
    op.add_column('animals', sa.Column('estimated_sex', sa.String(length=20), nullable=True))
    op.add_column('animals', sa.Column('sex_confidence', sa.Float(), nullable=True))
    op.add_column('animals', sa.Column('reid_embedding', sa.Text(), nullable=True))
    op.create_index(op.f('ix_animals_first_seen'), 'animals', ['first_seen'], unique=False)
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_last_seen'), 'animals', ['last_seen'], unique=False)
    op.create_index(op.f('ix_animals_rfid_tag'), 'animals', ['rfid_tag'], unique=True)
    op.drop_column('animals', 'estimated_age_class')
    op.drop_column('animals', 'estimated_gender')
    op.add_column('detections', sa.Column('detection_uid', sa.String(length=64), nullable=True))
    op.add_column('detections', sa.Column('center_x', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('center_y', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('gps_lon', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('gps_alt', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('image_path', sa.String(length=500), nullable=True))
    op.alter_column('detections', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_detections_detection_uid'), 'detections', ['detection_uid'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_detections_species'), 'detections', ['species'], unique=False)
    op.drop_column('detections', 'pos_x')
    op.drop_column('detections', 'pos_y')
    op.drop_column('detections', 'speed_mps')
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_index(op.f('ix_media_assets_timestamp'), 'media_assets', ['timestamp'], unique=False)
    op.add_column('reports', sa.Column('summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_reports_generated_at'), 'reports', ['generated_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_at'), table_name='reports')
    op.drop_column('reports', 'summary')
    op.drop_index(op.f('ix_media_assets_timestamp'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.add_column('detections', sa.Column('speed_mps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('detections', sa.Column('pos_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('detections', sa.Column('pos_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_detections_species'), table_name='detections')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_uid'), table_name='detections')
    op.alter_column('detections', 'animal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('detections', 'image_path')
    op.drop_column('detections', 'gps_alt')
    op.drop_column('detections', 'gps_lon')
    op.drop_column('detections', 'gps_lat')
    op.drop_column('detections', 'center_y')
    op.drop_column('detections', 'center_x')
    op.drop_column('detections', 'detection_uid')
    op.add_column('animals', sa.Column('estimated_gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('animals', sa.Column('estimated_age_class', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_animals_rfid_tag'), table_name='animals')
    op.drop_index(op.f('ix_animals_last_seen'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_first_seen'), table_name='animals')
    op.drop_column('animals', 'reid_embedding')
    op.drop_column('animals', 'sex_confidence')
    op.drop_column('animals', 'estimated_sex')
    op.drop_column('animals', 'age_confidence')
    op.drop_column('animals', 'estimated_age')
    op.drop_column('animals', 'rfid_tag')
    op.add_column('alerts', sa.Column('anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('media_asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('alerts_media_asset_id_fkey'), 'alerts', 'media_assets', ['media_asset_id'], ['id'])
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_column('alerts', 'video_path')
    op.drop_column('alerts', 'snapshot_path')
    op.drop_column('alerts', 'gps_lon')
    op.drop_column('alerts', 'gps_lat')
    op.drop_column('alerts', 'zone_name')
    op.create_table('health_metrics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('activity_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('stress_index', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rest_duration_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sleeping_duration_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feeding_duration_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('walking_distance_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('daily_movement_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('health_metrics_animal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('health_metrics_pkey'))
    )
    op.create_index(op.f('ix_health_metrics_date'), 'health_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_health_metrics_animal_id'), 'health_metrics', ['animal_id'], unique=False)
    op.create_table('behavior_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('behavior', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('window_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('anomaly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('camera_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('behavior_records_animal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('behavior_records_pkey'))
    )
    op.create_index(op.f('ix_behavior_records_timestamp'), 'behavior_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_behavior_records_animal_id'), 'behavior_records', ['animal_id'], unique=False)
    # ### end Alembic commands ###
